name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c244f422a4fa038a33cfaf8bdaf815493d76cfc158421a52c611809303f6279"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
