name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4eacbe184543359e561dda43c3a1b1f767423ea55f207b62f1cf71ada65766"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
