name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f98a674cd97cb320b5bbcb5f199d45834aabef588e4aaa4108b5c1b2ab881be4"

[versions]
fabric = "0.16.9"
minecraft = "1.21"
