name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac5892e41f9d456a4299b383078b56539ee58c36cea9a2b47cecb229d07652e8"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
