name = "MC1.21"
author = "TN_TechNoob"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4acc0f22c4815188dcdeb0614cc4f5f34b4676f0b91f80005f105fe2bd6d6e13"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
