name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5fad163ce4ef78e16ae92bfed1e709d88ce160bee6842c78306ed0666a866f"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
