name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a882b2cb4ef35feea024abd251a4c6ebad9ad12d30477153c5893edc8ded58d8"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
