name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adcdf504138d8ae9eecf6efad0b29687d6ca15811124bde9d1a5c14e010a6643"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
