name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d999c0e49af02ac893eaec7ac6ed47efd186070d7dfcc167ca6a2826427b5efe"

[versions]
fabric = "0.16.7"
minecraft = "1.21"
