name = "MC1.19.2"
author = "TN_TechNoob"
version = "v3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4033302d520848e52d5eb252d2fce5b3608add0afb0bbe46d50802b09b5b25ec"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
