name = "MC1.19.2"
author = "TN_TechNoob"
version = "v2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2061bec0f2aefc87744f591e7ad7c29342d2ee236532f7b1dffbcda82b6ab5fc"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"
