name = "MC1.19.2"
author = "TN_TechNoob"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04592015c1dd09d9007d9d057808df9b304ebc855ac33e0e6e61217a71fde70d"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"
