name = "MC1.19.2"
author = "TN_TechNoob"
version = "v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4346c9d44b498e14b10dad58f7f1f60e62f713850725aa2737a16fcaac4d7f0d"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
