name = "MC1.19.2"
author = "TN_TechNoob"
version = "v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8edc3cd49ebbba6ada3a959bba5df5c73b74b624206b0002ded11900227d66c"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
