name = "MC1.19.2"
author = "TN_TechNoob"
version = "v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cf055d1c0a26505c05c8c3ef85f82eab5b93b7ad964d77081be5032b0565f48"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
