name = "MC1.19.2"
author = "TN_TechNoob"
version = "v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "117ea9b20c5db177f8978c72a23dbda340dc65c1d638bb10ae9a0e9bd38416cc"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
