name = "MC1.19.2"
author = "TN_TechNoob"
version = "v4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4df7363282a6b98cbc756b37563878e6ba809f6e7a3b851e6ff5e30eded879f0"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"
