name = "MC1.19.2"
author = "TN_TechNoob"
version = "v3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494566916491fcabfaa7fcfe967dd408a1f0ff38fdcacfbeada02ad1e55a75cf"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
