name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dba7611c0900ad4ebbd30d7354cbf82b14e48a5a25badee1b4742b31f40f901a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
