name = "MC1.21.4"
author = "TN_TechNoob"
version = "v1.2.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab6327ce6ebd1e768dafdc35a57787a4a8a4fc07bb1f7117fc500d854161905"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
