name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfd2f5c3d09c49baab11915e81f82060a6e1ec2ab4eb839df9265696bfd8585f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
