name = "MC1.21.4"
author = "TN_TechNoob"
version = "v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b548e15ec67851d62ac1f169e49f24bede59bf72ba80226b8158a509d458b6d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
