name = "MC1.21.4"
author = "TN_TechNoob"
version = "v4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b60041bef7801f634b9a25fcfe0b26b1ead14bc93bdf8a843e89d6b4513c2df2"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
