name = "MC1.21.4"
author = "TN_TechNoob"
version = "v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a31f8d6bc29c85e29779d5f677c7123c5cb6ac34f64410d068985d1a9686a52"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
