name = "MC1.21.4"
author = "TN_TechNoob"
version = "v1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2635f383cc2146599f5967fe31c8785ca04605acf8e84f6123f11f6faaf3a9c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
