name = "MC1.21.1"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cad5b70a5643ac9153471ba3e78afaca3e1d359c5d676811acf5813306526406"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
