name = "1.20.1"
author = "TN_TechNoob"
version = "v7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "752df8025033b91acef8682539c0fb492dd85a8eaada1a7a06a2bcd40f13a116"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
