name = "1.20.1"
author = "TN_TechNoob"
version = "v7.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85cebf2df45990f3a8057e8b19606aca462d87aef37703fea41bf4f2c6af19e4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
