name = "1.20.1"
author = "TN_TechNoob"
version = "v8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d3aa22e8dfc5b4188747b6d08c2868b5f597ae2f14f6da10097ee8a45f4bcec"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
