name = "1.20.1"
author = "TN_TechNoob"
version = "v8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b887023b5aa3144d76a2cc23b25ab42081694e91d59fdb5282fa36bfff713fe6"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
