name = "1.20.1"
author = "TN_TechNoob"
version = "v7.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35d69f969619c4f6847e601639bae16e88e184385b0164d72da5a4c1e2ab7c16"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
