name = "1.20.1"
author = "TN_TechNoob"
version = "v7.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c11655de5529f0804a16a65699b1dc0ce6269a832c4dce1fbbcda25513e7fc70"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
