name = "1.20.1"
author = "TN_TechNoob"
version = "v8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24f3b484d0ee99339701ac290d5683dec29452c8f9855b98c971ddfc1eae1a69"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
