name = "1.20.1"
author = "TN_TechNoob"
version = "v9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c9fd66a2d5619b6a32d3e22f578fcaf191cd423da2a76e7353bb3444ef384d8"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
