name = "MC1.20.6"
author = "TN_TechNoob"
version = "v2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9cc3d8654815d3eee4e9deb93a5138483cf2d86d45a1fe882f5093dbd7d9ff1"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
