name = "MC1.18.2"
author = "TN_TechNoob"
version = "v11.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6965a9269e7537010dd1b7e284251981008aa4d8462fa3cd40fe00db5fe4171a"

[versions]
fabric = "0.16.9"
minecraft = "1.18.2"
