name = "MC1.18.2"
author = "TN_TechNoob"
version = "v13.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fde12aa54c37a4dd1f9731bd9c0fb4bfb8cf75f516ed2768d27d3ecbfc43b56b"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
