name = "MC1.18.2"
author = "TN_TechNoob"
version = "v11.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c72b809d002610fa0b994740fc10e2c1de6588010e085e2aa476cab99744d84"

[versions]
fabric = "0.16.5"
minecraft = "1.18.2"
