name = "MC1.18.2"
author = "TN_TechNoob"
version = "v12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5527af5e70ae3e19a529ebb7d3d0510b7cd1c5b0a84ec557caa28132d95f0734"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
