name = "MC1.18.2"
author = "TN_TechNoob"
version = "v11.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fb826e17b7c3f7437157931735affd0374b1dade2519a7f81cf1fc2651d1ec1"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
