name = "MC1.18.2"
author = "TN_TechNoob"
version = "v12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa51df76775a0ebb82caee9ad66374d18722d067ffddcc53d07e5452f806f31f"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
