name = "MC1.18.2"
author = "TN_TechNoob"
version = "v11.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c109ca6f0c9e81d8c45c8af249ebd94b79a9d5767bcbbfdc2a22c9bc9c36ba3b"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
