name = "MC1.18.2"
author = "TN_TechNoob"
version = "v13.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36c1caa93db4d9c7d1f0bd41a90354219057db8b6eb337c18d7290f018a139ba"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
