name = "MC1.18.2"
author = "TN_TechNoob"
version = "v12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c65d85263828726c887efe2ba8f54669bfe63bae7e5bb502ad52504de6c9c2"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
