name: Automatically publish to Modrinth
on: workflow_dispatch
jobs:
  publish-to-modrinth:
    if: github.repository_owner == 'TN-TechNoob'
    runs-on: ubuntu-22.04
    environment: github-actions
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
        - name: Clone Repo
          uses: actions/checkout@v4
        - name: Download packwiz
          uses: actions/download-artifact@v4
          with:
            name: "Linux 64-bit x86"
            github-token: ${{ secrets.PERSONAL_TOKEN }}
            repository: packwiz/packwiz
            run-id: 9259662367
        - name: Export to packwiz
          run: |
            chmod +x ./packwiz
            pushd Packwiz/${{ vars.MC_VERSION }}
            ../../packwiz modrinth export
            popd
        - name: Attest mrpack
          id: attest-mrpack
          uses: actions/attest-build-provenance@v1
          with:
            subject-path: MC${{ vars.MC_VERSION }}-${{ vars.PACK_VERSION }}.mrpack
        - name: Publish to Modrinth
          uses: Kir-Antipov/mc-publish@v3.3
          with:
            modrinth-id: Ohwb2cTF
            modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
