name: Automatically publish to Modrinth
on: 
  release:
    types: [published]
jobs:
  publish-to-modrinth:
    if: github.repository_owner == 'TN-TechNoob'
    runs-on: ubuntu-24.04
    environment: github-actions
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
        - name: Clone Repo
          uses: actions/checkout@v4
        - name: Download packwiz
          uses: actions/download-artifact@v4
          with:
            name: "Linux 64-bit x86"
            github-token: ${{ secrets.PERSONAL_TOKEN }}
            repository: TN-TechNoob/packwiz
            run-id: 12161716944
        - name: Export to packwiz
          run: |
            chmod +x ./packwiz
            pushd Packwiz/${{ vars.MC_VERSION }}
            ../../packwiz modrinth export -o ../../TNVBP_MC${{ vars.MC_VERSION }}-${{ github.ref_name }}.mrpack
            popd
        - name: Attest mrpack
          id: attest-mrpack
          uses: actions/attest-build-provenance@v1
          with:
            subject-path: TNVBP_MC${{ vars.MC_VERSION }}-${{ github.ref_name }}.mrpack
        - name: Publish to Modrinth
          uses: Kir-Antipov/mc-publish@v3.3
          with:
            name: TNVBP MC${{ vars.MC_VERSION }}-${{ github.ref_name }}
            modrinth-id: Ohwb2cTF
            modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
            files: TNVBP_MC${{ vars.MC_VERSION }}-${{ github.ref_name }}.mrpack
            loaders: fabric
            game-versions: ${{ vars.MC_VERSION }}
        - name: Upload to Github
          uses: Shopify/upload-to-release@v2.0.0
          with:
            name: TNVBP_MC${{ vars.MC_VERSION }}-${{ github.ref_name }}.mrpack
            path: TNVBP_MC${{ vars.MC_VERSION }}-${{ github.ref_name }}.mrpack
            repo-token: ${{ secrets.GITHUB_TOKEN }}
