name: Build

on:
  push:
    branches: ["main"]
  pull_request: 
jobs:
  build:
    strategy:
      matrix:
        mc_version: ["1.18.2", "1.19.2", "1.19.4", "1.20.1", "1.20.6", "1.21"]
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Check for changes
        id: check-for-changes
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              CHANGED_VERSION=$(git diff --quiet--name-only -r HEAD^1 HEAD Packwiz/${{ matrix.mc_version }})
          else
              CHANGED_VERSION=$(git diff --quiet --name-only ${{ github.event.before }} ${{ github.event.after }} Packwiz/${{ matrix.mc_version }})
          fi

          if [ $CHANGED_VERSION ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Build Pack
        if: steps.check-for-changes.outputs.changed == 'true'
        run: |
          sudo apt-get install -y unzip zip curl
          wget -O packwiz.zip "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip" && unzip ./packwiz.zip && rm -rf ./packwiz.zip
          mkdir -p /tmp/dist
          chmod +x ./packwiz && mv ./packwiz /tmp/packwiz
          pushd Packwiz/${{ matrix.mc_version}}
          PACK_VERSION=$(grep -oP 'version = "\K[^"]+' "pack.toml")
          echo "PACK_VERSION=$(PACK_VERSION)" >> $GITHUB_ENV
          /tmp/packwiz modrinth export -o /tmp/dist/TNVBP_${{ matrix.mc_version}}-$PACK_VERSION.mrpack
          popd
      - name: Attest mrpack
        id: attest-mrpack
        if: steps.check-for-changes.outputs.changed == 'true'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: /tmp/dist/*
      - uses: actions/upload-artifact@v4
        if: steps.check-for-changes.outputs.changed == 'true'
        with:
          name: ${{ matrix.mc_version }}-${{ env.PACK_VERSION }}
          path: /tmp/dist/
