name: Update MC_VERSION Based on Branch Name
on: workflow_dispatch
env: 
  TEST_VAR: test
jobs:
  update-mc-version:
    if: github.repository_owner == 'TN-TechNoob'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set MC_VERSION from branch name
        run: echo "{{ env.TEST_VAR }}" >> $MC_VERSION
