name: Update MC_VERSION Based on Branch Name
on:
  pull_request:
    types:
      - opened
jobs:
  update-mc-version:
    if: github.repository_owner == 'TN-TechNoob'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: |
            gh variable list
            gh variable set MC_VERSION --body "${GITHUB_REF_NAME}"
            gh variable list
        env: 
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}