name = "MC1.19.4"
author = "TN_TechNoob"
version = "v12.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beeba16a54327cbb98cf39ea3ae0a0b5b79645d6a91b4be3fdc802049d113b8c"

[versions]
fabric = "0.16.7"
minecraft = "1.19.4"
