name = "MC1.19.4"
author = "TN_TechNoob"
version = "v13.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb2f797ca6b6b8af17633794feb4124ba15f4413c6d995f476ecbe4f49e4f129"

[versions]
fabric = "0.16.7"
minecraft = "1.19.4"
