name = "MC1.19.4"
author = "TN_TechNoob"
version = "v12.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8401e6e8b961c972d03590768b65d6be00de1510e5f4e8d71050ca8cfaa4c3d8"

[versions]
fabric = "0.16.3"
minecraft = "1.19.4"
